[package]
name = "productivity_gui"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
csv = "1.3.1"
iced = { version = "0.9.0", features = ["tokio", "canvas"] }
serde = { version = "1.0.219", features = ["derive"] }
